create extension if not exists pgcrypto;

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  status text not null default 'planned' check (status in ('planned','active','on_hold','completed','archived')),
  start_date date,
  target_date date,
  completed_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  title text not null,
  description text,
  status text not null default 'backlog' check (status in ('backlog','todo','in_progress','review','done')),
  priority text not null default 'medium' check (priority in ('low','medium','high','critical')),
  due_at timestamptz,
  estimate_minutes integer check (estimate_minutes is null or estimate_minutes >= 0),
  actual_minutes integer not null default 0 check (actual_minutes >= 0),
  notes text,
  is_recurring boolean not null default false,
  recurrence_rule jsonb,
  recurrence_timezone text,
  recurring_template_id uuid references public.tasks(id) on delete set null,
  occurrence_key text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, recurring_template_id, occurrence_key)
);

create table public.task_occurrences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  template_task_id uuid not null references public.tasks(id) on delete cascade,
  task_id uuid references public.tasks(id) on delete set null,
  occurrence_key text not null,
  scheduled_for timestamptz not null,
  status text not null default 'pending' check (status in ('pending','generated','skipped','completed')),
  generated_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, template_task_id, occurrence_key)
);

create table public.subtasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id uuid not null references public.tasks(id) on delete cascade,
  title text not null,
  is_completed boolean not null default false,
  position integer not null default 0,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tags (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  color text,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table public.task_tags (
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id uuid not null references public.tasks(id) on delete cascade,
  tag_id uuid not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (task_id, tag_id)
);

create table public.reminders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id uuid references public.tasks(id) on delete cascade,
  project_id uuid references public.projects(id) on delete cascade,
  remind_at timestamptz not null,
  message text,
  is_read boolean not null default false,
  dismissed_at timestamptz,
  created_at timestamptz not null default now(),
  check ((task_id is not null)::int + (project_id is not null)::int = 1)
);

create table public.task_status_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id uuid not null references public.tasks(id) on delete cascade,
  from_status text check (from_status is null or from_status in ('backlog','todo','in_progress','review','done')),
  to_status text not null check (to_status in ('backlog','todo','in_progress','review','done')),
  changed_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = public as $$
begin new.updated_at = now(); return new; end; $$;

create or replace function public.log_task_status_change()
returns trigger language plpgsql security invoker set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.task_status_events(user_id, task_id, from_status, to_status, changed_at)
    values (new.user_id, new.id, null, new.status, now());
  elsif new.status is distinct from old.status then
    insert into public.task_status_events(user_id, task_id, from_status, to_status, changed_at)
    values (new.user_id, new.id, old.status, new.status, now());
  end if;
  return new;
end; $$;

create trigger projects_set_updated_at before update on public.projects for each row execute function public.set_updated_at();
create trigger tasks_set_updated_at before update on public.tasks for each row execute function public.set_updated_at();
create trigger subtasks_set_updated_at before update on public.subtasks for each row execute function public.set_updated_at();
create trigger tasks_log_status after insert or update of status on public.tasks for each row execute function public.log_task_status_change();

create index projects_user_status_idx on public.projects(user_id, status);
create index tasks_user_status_idx on public.tasks(user_id, status);
create index tasks_user_due_idx on public.tasks(user_id, due_at);
create index tasks_project_idx on public.tasks(project_id);
create index task_occurrences_schedule_idx on public.task_occurrences(user_id, scheduled_for);
create index reminders_user_time_idx on public.reminders(user_id, remind_at);
create index task_status_events_task_idx on public.task_status_events(task_id, changed_at);

alter table public.projects enable row level security;
alter table public.tasks enable row level security;
alter table public.task_occurrences enable row level security;
alter table public.subtasks enable row level security;
alter table public.tags enable row level security;
alter table public.task_tags enable row level security;
alter table public.reminders enable row level security;
alter table public.task_status_events enable row level security;

create policy "projects_select_own" on public.projects for select to authenticated using ((select auth.uid()) = user_id);
create policy "projects_insert_own" on public.projects for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "projects_update_own" on public.projects for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "projects_delete_own" on public.projects for delete to authenticated using ((select auth.uid()) = user_id);
create policy "tasks_select_own" on public.tasks for select to authenticated using ((select auth.uid()) = user_id);
create policy "tasks_insert_own" on public.tasks for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "tasks_update_own" on public.tasks for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "tasks_delete_own" on public.tasks for delete to authenticated using ((select auth.uid()) = user_id);
create policy "occurrences_select_own" on public.task_occurrences for select to authenticated using ((select auth.uid()) = user_id);
create policy "occurrences_insert_own" on public.task_occurrences for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "occurrences_update_own" on public.task_occurrences for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "occurrences_delete_own" on public.task_occurrences for delete to authenticated using ((select auth.uid()) = user_id);
create policy "subtasks_select_own" on public.subtasks for select to authenticated using ((select auth.uid()) = user_id);
create policy "subtasks_insert_own" on public.subtasks for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "subtasks_update_own" on public.subtasks for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "subtasks_delete_own" on public.subtasks for delete to authenticated using ((select auth.uid()) = user_id);
create policy "tags_select_own" on public.tags for select to authenticated using ((select auth.uid()) = user_id);
create policy "tags_insert_own" on public.tags for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "tags_update_own" on public.tags for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "tags_delete_own" on public.tags for delete to authenticated using ((select auth.uid()) = user_id);
create policy "task_tags_select_own" on public.task_tags for select to authenticated using ((select auth.uid()) = user_id);
create policy "task_tags_insert_own" on public.task_tags for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "task_tags_delete_own" on public.task_tags for delete to authenticated using ((select auth.uid()) = user_id);
create policy "reminders_select_own" on public.reminders for select to authenticated using ((select auth.uid()) = user_id);
create policy "reminders_insert_own" on public.reminders for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "reminders_update_own" on public.reminders for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "reminders_delete_own" on public.reminders for delete to authenticated using ((select auth.uid()) = user_id);
create policy "task_status_events_select_own" on public.task_status_events for select to authenticated using ((select auth.uid()) = user_id);
